### PR TITLE
Create action to hover over an element

### PR DESCRIPTION
**Pull request by Bassoon08**
Use Selenium ActionChains to hover over an element by either the element object or the identifier of the element.
@rmdaggett @cdangg @rtabor

### CODE REVIEW

**Comment by Ry4an** [comment]
Just wanna say how great it is to see someone other than @rmdaggett doing PRs into this repo.  Huzzah!

**Comment by Bassoon08** [comment]
thanks @Ry4an!

**Comment by rtabor** [comment]
Tested this out in Chrome and Firefox. LGTM

**Comment by rmdaggett** [comment]
woot :) LGTM!

**Pull request merged**
