### PR TITLE
rd-add-poll-for-visibility

### PR DESCRIPTION
**Pull request by rmdaggett**
Add poll_for_visibility action which takes an id or element, wait, and frequecny arguments to poll the DOM until the element becomes visible. Raises an AssertionError if the element does not become visible after the specified wait time.

cc @cdangg @Bassoon08 @rtabor

### CODE REVIEW

**Comment by Bassoon08** [comment]
Actually I just realized, do you want to print something other than the web element object in the exception? It will say something like this, but I don't know how useful that is:

```
Exception: Element is not visible. <selenium.webdriver.remote.webelement.WebElement object at 0x10648fc90>
 ```

**Comment by Bassoon08** [comment]
If we get a failure, we'll see what line it's on, maybe `Element is not visible` is enough (we have so much logging anyway).

**Comment by rmdaggett** [comment]
No you're right, I had intended to add that but missed it. How about now??

**Comment by rmdaggett** [comment]
OK should be all set now @Bassoon08

**Comment by Bassoon08** [comment]
LGTM!

**Pull request merged**
